name: CI

on:
  push:
    branches: 
      - '*'
    tags:
      - '!*'
  pull_request:
    branches: 
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.3.x', '2.4.x', '2.5.x', '2.6.x']
    steps:
    - uses: actions/checkout@v1
    - name: Setup Ruby ${{ matrix.ruby }}
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        architecture: 'x64'
    - name: Lint and Test
      run: |
        gem install bundler -N
        bundle install --jobs 4 --retry 3
        bundle exec rake ci
